global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.Extensions.Configuration;
global using Testcontainers.PostgreSql;
global using System.Net;
global using System.Net.Http.Json;
global using BuildingBlocks.Application.Extensions;
global using Todos.Application.Views;
global using AwesomeAssertions;
